extern void write_split_mode_Mem(int * mem);
extern void write_cu_data_mvd_Mem(int * mem);
extern void write_cu_data_pb_part_Mem(int * mem);
extern void write_cu_data_tb_part_Mem(int * mem);
extern void write_cu_data_pred_mode_Mem(int * mem);
extern void write_cu_data_mvr_idx_Mem(int * mem);
extern void write_cu_data_umve_flag_Mem(int * mem);
extern void write_cu_data_umve_idx_Mem(int * mem);
extern void write_cu_data_skip_idx_Mem(int * mem);
extern void write_cu_data_affine_flag_Mem(int * mem);
extern void write_cu_data_ipf_flag_Mem(int * mem);
extern void write_cu_data_mvp_from_hmvp_flag_Mem(int * mem);
extern void write_cu_data_mpm_Mem(int * mem);
extern void write_cu_data_ipm_Mem(int * mem);
extern void write_cu_data_refi_Mem(int * mem);
extern void write_cu_data_num_nz_coef_Mem(int * mem);
extern void write_rpm_num_refp_Mem(int * mem);
extern void write_coef_Mem(int * mem);
extern void write_modeIdc_Mem(int * mem);
extern void write_typeIdc_Mem(int * mem);
extern void write_startBand_Mem(int * mem);
extern void write_startBand2_Mem(int * mem);
extern void write_deltaband_Mem(int * mem);
extern void write_slice_sao_enable_Mem(int * mem);
extern void write_offset_Mem(int * mem);
extern void write_me_line_map_ptr_map_scu_inner_Mem(int * mem);
extern void write_me_line_map_ptr_map_cu_mode_inner_Mem(int * mem);
extern void write_me_line_map_ptr_map_scu_above_line_Mem(int * mem);
extern void write_me_line_map_ptr_map_cu_mode_above_line_Mem(int * mem);
write_split_mode_Mem(split_mode);
write_cu_data_mvd_Mem(cu_data_mvd);
write_cu_data_pb_part_Mem(cu_data_pb_part);
write_cu_data_tb_part_Mem(cu_data_tb_part);
write_cu_data_pred_mode_Mem(cu_data_pred_mode);
write_cu_data_mvr_idx_Mem(cu_data_mvr_idx);
write_cu_data_umve_flag_Mem(cu_data_umve_flag);
write_cu_data_umve_idx_Mem(cu_data_umve_idx);
write_cu_data_skip_idx_Mem(cu_data_skip_idx);
write_cu_data_affine_flag_Mem(cu_data_affine_flag);
write_cu_data_ipf_flag_Mem(cu_data_ipf_flag);
write_cu_data_mvp_from_hmvp_flag_Mem(cu_data_mvp_from_hmvp_flag);
write_cu_data_mpm_Mem(cu_data_mpm);
write_cu_data_ipm_Mem(cu_data_ipm);
write_cu_data_refi_Mem(cu_data_refi);
write_cu_data_num_nz_coef_Mem(cu_data_num_nz_coef);
write_rpm_num_refp_Mem(rpm_num_refp);
write_coef_Mem(coef);
write_modeIdc_Mem(modeIdc);
write_typeIdc_Mem(typeIdc);
write_startBand_Mem(startBand);
write_startBand2_Mem(startBand2);
write_deltaband_Mem(deltaband);
write_slice_sao_enable_Mem(slice_sao_enable);
write_offset_Mem(offset);
write_me_line_map_ptr_map_scu_inner_Mem(me_line_map_ptr_map_scu_inner);
write_me_line_map_ptr_map_cu_mode_inner_Mem(me_line_map_ptr_map_cu_mode_inner);
write_me_line_map_ptr_map_scu_above_line_Mem(me_line_map_ptr_map_scu_above_line);
write_me_line_map_ptr_map_cu_mode_above_line_Mem(me_line_map_ptr_map_cu_mode_above_line);
